#!/usr/bin/env python
# -*- coding: latin-1 -*-
dosya=open("belgeuser.txt","w")

dosya.write("""


kontrol = True 
while kontrol:
    k_adi = input("harflerden olusan bir kullanici adi giriniz:")
    harfler = "ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZabcçdefgğhıijklmnoöprsştuüvyz"
    uzunluk = len(k_adi) 

    if uzunluk in range(3, 18): 
        a = 0
        for harf in k_adi:  
            if harf in harfler:
                a = a + 1  
        if  a == uzunluk:
            print("gecerli bir kullanici")
            break
    else:
        print("tekrar deneyin")
        continue
kontrol = True
while kontrol:
    
    k_sifre = input("rakamlardan olusan bir sifre giriniz:")
    rakamlar = "0123456789"
    uzunluk = len(k_sifre)
    

    if uzunluk in range(6, 12):
        a = 0
        for rakam in k_sifre:  
            if rakam in rakamlar:
             a = a + 1  
    if a == uzunluk:  
        print("gecerli bir sifre girdiniz")
        print("\nsifreniz ve kullanici adiniz basariyla kaydedildi.")
        break
    else:
        print("tekrar deneyin")
        continue 
        """)
dosya.close()
